### ISSUE TITLE
Gadgetbridge notifications

### ISSUE THREAD

**Issue by dapgo** [jeffmer/WatchApps#3]
Would it be possible to port the bangle "GadgetBridge" apps to Watchapps?

[Android Integration](https://github.com/espruino/BangleApps/tree/master/apps/android)
[Messages](https://github.com/espruino/BangleApps/tree/master/apps/messages)

I haven't tried to install  but I assume that required functions from bangle will be missing here.

**Comment by jeffmer** [comment]
Correction, you need to add the line:

`if(STOR.read("android.boot.js")) eval(STOR.read("android.boot.js"));`

at the end of `main.js`

**Comment by dapgo** [comment]
Before I was trying without success with:
 
if(require("Storage").read("android.boot.js")) eval(require("Storage").read("android.boot.js")); 

and
NRF.setAdvertising({},{name:"espruino"});

but GB is/was not discovering the device

**Comment by jeffmer** [comment]
HI, I got hold of an oldish Android phone (5.0.1) and got in to run  gadgetBridge. I did manage to connect to a P8 running the apps, however, I could not connect to a magic3, mostly because the GadgetBridge app crashed after it discovered three devices. Did not manage to get much further with the connect device - not sure how to debug.

**Comment by jeffmer** [comment]
OK, if you update your **main** module from the repository (delete it and reload), notifications should now work. I will leave it open until you confirm that you gave got it to work with the real GB. I tested it with a message typed at the Web IDE console:
`GB({t:"notify", id:5, src:"gadget",title:"Test",body:"message"});`

**Comment by dapgo** [comment]
Yes, it works 💯 

The only remark is that I had to add a step(upload lcp-p8.js) in the middle of removing and installing, because installation was failing 
Uncaught ReferenceError: "p" is not defined 

at console it was more verbose 
Uncaught ReferenceError: "ST7789" is not defined
 at line 10 col 4 in main.js
var g=ST7789();
      ^
>Uncaught Error: Cannot read property 'drawRect' of undefined
 at line 1 col 2
g.drawRect(10,g.getHeight()-16,g.getWidth()-10,g.getHeight()...
 ^
>Uncaught ReferenceError: "p" is not defined
 at line 1 col 1287
...muVluM6myKDvs7")),0,1253);;p(7);Bluetooth.println("OK")

**Comment by jeffmer** [comment]
I thought the new version of boot had fixed that. Anyway, I will close this issue!
