### ISSUE TITLE
Magic 3 touch, accel and build sources

### ISSUE THREAD

**Issue by Chriz76** [jeffmer/WatchApps#9]
Hello and thank you for your great work!

Is the touch screen and the accelorator working on the Magic 3?

Is this the repo that you used for your magic 3 build and can I use it in the current state on the master branch as basis for own magic 3 builds:https://github.com/jeffmer/Espruino/blob/master/boards/Magic3.py

**Comment by jeffmer** [comment]
Yes, both touch and accelerator are working and yes, that’s the correct board file. 

You will also need to add my version of lcd_spi_unbuf to the standard repository to build it. Hopefully that should work. I am afraid that I have not built it for some time.

**Comment by Chriz76** [comment]
That's great thank you!

**Comment by Chriz76** [comment]
Thank you so much. That's great!
